import React, { useState } from 'react';
import { StoryboardScene } from '@/lib/storyboard-parser';
import { Badge } from '@/components/ui/badge';
import { Clapperboard, Monitor, Download, Maximize2, Loader2, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { saveStoryboardImageAction } from '@/app/actions/save-storyboard-image';
import { useToast } from '@/hooks/use-toast';
import { Dialog, DialogContent, DialogTitle } from '@/components/ui/dialog';
import { cn } from '@/lib/utils';

interface NanoBananaRendererProps {
    scenes: StoryboardScene[];
    generatedImages: { [key: string]: string };
    setGeneratedImages: React.Dispatch<React.SetStateAction<{ [key: string]: string }>>;
    sessionTimestamp: string;
}

export function NanoBananaRenderer({ scenes, generatedImages, setGeneratedImages, sessionTimestamp }: NanoBananaRendererProps) {
    // This component acts as a high-fidelity cinematic review stage
    // for the storyboards generated by the Nano Banana 2 engine.
    const [isExporting, setIsExporting] = useState(false);
    const [zoomedImage, setZoomedImage] = useState<string | null>(null);
    const [enhancingPanels, setEnhancingPanels] = useState<{ [key: string]: boolean }>({});
    const { toast } = useToast();

    // Helper to get panel ID
    const getPanelId = (sceneIdx: number, gridIdx: number) => `scene-${sceneIdx + 1}-grid-${gridIdx + 1}`;

    const handleEnhanceCharacter = async (sceneIdx: number, gridIdx: number) => {
        const panelId = getPanelId(sceneIdx, gridIdx);
        setEnhancingPanels(prev => ({ ...prev, [panelId]: true }));

        try {
            const { enhanceCharacterAction } = await import('@/app/actions/enhance-character');
            const result = await enhanceCharacterAction(sceneIdx + 1, gridIdx + 1, sessionTimestamp);

            if (result.success && result.masterDataUri) {
                const sceneId = scenes[sceneIdx].id;
                setGeneratedImages(prev => ({ ...prev, [sceneId]: result.masterDataUri! }));
                toast({
                    title: "Enhancement Successful",
                    description: `Character enhanced for Scene ${sceneIdx + 1}, Panel ${gridIdx + 1}. Storyboard updated.`,
                });
            } else {
                throw new Error(result.message);
            }
        } catch (error: any) {
            toast({
                title: "Enhancement Failed",
                description: error.message || "Failed to reach ComfyUI or process image.",
                variant: "destructive"
            });
        } finally {
            setEnhancingPanels(prev => ({ ...prev, [panelId]: false }));
        }
    };

    const handleExportArchive = async () => {
        const imagesToExport = Object.entries(generatedImages);
        if (imagesToExport.length === 0) {
            toast({
                title: "No Images to Export",
                description: "Please generate your visual scenes first.",
                variant: "destructive"
            });
            return;
        }

        setIsExporting(true);

        // Format: YYYYMMDD-HHMM
        const now = new Date();
        const timestamp = now.getFullYear().toString() +
            (now.getMonth() + 1).toString().padStart(2, '0') +
            now.getDate().toString().padStart(2, '0') + '-' +
            now.getHours().toString().padStart(2, '0') +
            now.getMinutes().toString().padStart(2, '0');

        try {
            for (let i = 0; i < scenes.length; i++) {
                const scene = scenes[i];
                const dataUri = generatedImages[scene.id];

                if (dataUri) {
                    await saveStoryboardImageAction(i, dataUri, timestamp);
                }
            }

            toast({
                title: "Archive Successful",
                description: `All ${imagesToExport.length} storyboards saved to /storyboard/${timestamp}`,
            });
        } catch (error: any) {
            toast({
                title: "Export Error",
                description: error.message || "Failed to save archive to disk.",
                variant: "destructive"
            });
        } finally {
            setIsExporting(false);
        }
    };

    return (
        <div className="mt-24 space-y-12 pb-24">
            <div className="flex flex-col md:flex-row items-end justify-between gap-6 border-b border-white/10 pb-8">
                <div className="space-y-2">
                    <div className="flex items-center gap-2 mb-2">
                        <Badge variant="outline" className="text-[10px] uppercase font-bold tracking-widest bg-primary/10 border-primary/20 text-primary">
                            Final Output
                        </Badge>
                        <div className="h-1 w-1 rounded-full bg-white/20" />
                        <span className="text-[10px] uppercase font-bold tracking-widest text-muted-foreground">Studio Rendering v2.1</span>
                    </div>
                    <h2 className="text-4xl font-headline font-bold">AIFX Cast <span className="text-primary italic">Cinema Review</span></h2>
                    <p className="text-muted-foreground max-w-xl text-sm leading-relaxed">
                        Technical review and sequence mastery. Your 4-panel grids are compiled here for
                        professional continuity checks and final export approval.
                    </p>
                </div>

                <div className="flex gap-3">
                    <div className="flex items-center glass-panel border border-white/10 px-4 uppercase text-[10px] tracking-widest font-bold h-10 text-muted-foreground/70">
                        <Monitor className="h-3.5 w-3.5 mr-2" />
                        Full Sequence
                    </div>
                    <Button
                        className="cinematic-gradient uppercase text-[10px] tracking-widest font-bold h-10 px-6"
                        onClick={handleExportArchive}
                        disabled={isExporting}
                    >
                        {isExporting ? (
                            <Loader2 className="h-3.5 w-3.5 mr-2 animate-spin" />
                        ) : (
                            <Download className="h-3.5 w-3.5 mr-2" />
                        )}
                        Export Archive
                    </Button>
                </div>
            </div>

            <div className="grid grid-cols-1 gap-16">
                {scenes.map((scene, idx) => {
                    const imageUrl = generatedImages[scene.id];
                    return (
                        <div key={scene.id} className="group relative">
                            <div className="flex flex-col md:flex-row gap-8 items-start">
                                <div className="w-full md:w-2/3 space-y-6">
                                    <div className="relative overflow-hidden rounded-2xl border border-white/5 bg-black/40 shadow-2xl transition-all duration-500 group-hover:border-primary/20">
                                        <div className="aspect-video relative group-hover:scale-[1.01] transition-transform duration-700">
                                            {imageUrl ? (
                                                <img
                                                    src={imageUrl}
                                                    alt={`Scene ${scene.sceneNumber}`}
                                                    className="w-full h-full object-cover"
                                                />
                                            ) : (
                                                <div className="absolute inset-0 flex items-center justify-center">
                                                    <div className="text-center space-y-4 opacity-40 group-hover:opacity-60 transition-opacity">
                                                        <div className="h-20 w-20 mx-auto rounded-full border-2 border-dashed border-white/20 flex items-center justify-center">
                                                            <Clapperboard className="h-8 w-8 text-white/50" />
                                                        </div>
                                                        <p className="text-[10px] font-bold uppercase tracking-[0.2em]">Scene {scene.sceneNumber} Cinema Feed</p>
                                                        <p className="text-[8px] font-mono text-white/30 uppercase tracking-[0.1em]">Awaiting Visual Production</p>
                                                    </div>
                                                </div>
                                            )}

                                            <div className="absolute top-6 left-6 flex flex-col gap-1 items-start">
                                                <span className="bg-black/80 backdrop-blur-md px-3 py-1 rounded text-[10px] font-mono font-bold text-primary tracking-widest">
                                                    SCENE_{scene.sceneNumber.toString().padStart(3, '0')}
                                                </span>
                                                <span className="bg-white/10 backdrop-blur-md px-3 py-1 rounded text-[10px] font-mono font-bold text-white/50 tracking-widest">
                                                    CAM_A_STUDIO
                                                </span>
                                            </div>

                                            {imageUrl && (
                                                <div className={cn(
                                                    "absolute inset-0 grid grid-cols-2 grid-rows-2 transition-opacity duration-300",
                                                    [0, 1, 2, 3].some(g => enhancingPanels[getPanelId(idx, g)]) 
                                                        ? "opacity-100" 
                                                        : "opacity-0 group-hover:opacity-100"
                                                )}>
                                                    {[0, 1, 2, 3].map((gIdx) => {
                                                        const panelId = getPanelId(idx, gIdx);
                                                        const isEnhancing = enhancingPanels[panelId];
                                                        return (
                                                            <div 
                                                                key={gIdx} 
                                                                className={cn(
                                                                    "relative flex items-center justify-center border border-white/10 transition-colors group/panel overflow-hidden",
                                                                    isEnhancing ? "bg-black/40" : "hover:bg-white/5"
                                                                )}
                                                            >
                                                                <Button
                                                                    size="sm"
                                                                    variant="secondary"
                                                                    className={cn(
                                                                        "bg-black/60 backdrop-blur-md border-white/20 text-[8px] uppercase font-bold tracking-widest h-8 transition-all",
                                                                        isEnhancing 
                                                                            ? "opacity-100 translate-y-0" 
                                                                            : "opacity-0 group-hover/panel:opacity-100 translate-y-2 group-hover/panel:translate-y-0 hover:bg-primary hover:text-white"
                                                                    )}
                                                                    onClick={() => handleEnhanceCharacter(idx, gIdx)}
                                                                    disabled={isEnhancing}
                                                                >
                                                                    {isEnhancing ? (
                                                                        <Loader2 className="h-3 w-3 mr-1 animate-spin" />
                                                                    ) : (
                                                                        <Clapperboard className="h-3 w-3 mr-1" />
                                                                    )}
                                                                    {isEnhancing ? "Enhancing..." : "Enhance Character"}
                                                                </Button>
                                                            </div>
                                                        );
                                                    })}
                                                </div>
                                            )}

                                            {imageUrl && (
                                                <div className="absolute bottom-6 right-6 opacity-0 group-hover:opacity-100 transition-all duration-500 transform translate-y-2 group-hover:translate-y-0 z-10">
                                                    <Button
                                                        size="icon"
                                                        variant="secondary"
                                                        className="bg-white/10 backdrop-blur-xl border-white/20 h-10 w-10 rounded-full hover:bg-primary hover:text-white transition-all"
                                                        onClick={() => setZoomedImage(imageUrl)}
                                                    >
                                                        <Maximize2 className="h-4 w-4" />
                                                    </Button>
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                </div>

                                <div className="w-full md:w-1/3 space-y-8 py-4">
                                    <div className="space-y-4">
                                        <div className="flex items-center gap-3">
                                            <div className="h-0.5 w-8 bg-primary rounded-full" />
                                            <h3 className="text-xs font-bold uppercase tracking-[0.3em] text-primary/80">Cinematography</h3>
                                        </div>
                                        <h4 className="text-2xl font-headline font-bold leading-tight group-hover:text-primary transition-colors">
                                            Sequence {idx + 1}: {scene.sceneNumber}
                                        </h4>
                                        <div className="prose prose-invert prose-sm max-w-none">
                                            <p className="text-muted-foreground/80 leading-relaxed italic border-l-2 border-white/5 pl-4 py-1">
                                                {scene.imagePrompt.split('Technical Constraints:')[0].trim()}
                                            </p>
                                        </div>
                                    </div>

                                    <div className="grid grid-cols-2 gap-4">
                                        <div className="p-4 rounded-xl bg-white/[0.02] border border-white/5 space-y-1">
                                            <span className="text-[8px] font-bold uppercase tracking-widest text-muted-foreground/50 block">Pacing</span>
                                            <span className="text-xs font-bold font-mono">24.0 FPS</span>
                                        </div>
                                        <div className="p-4 rounded-xl bg-white/[0.02] border border-white/5 space-y-1">
                                            <span className="text-[8px] font-bold uppercase tracking-widest text-muted-foreground/50 block">Optics</span>
                                            <span className="text-xs font-bold font-mono">35MM PRIME</span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {idx < scenes.length - 1 && (
                                <div className="mt-16 w-full h-px bg-gradient-to-r from-transparent via-white/5 to-transparent" />
                            )}
                        </div>
                    );
                })}
            </div>

            <Dialog open={!!zoomedImage} onOpenChange={(open) => !open && setZoomedImage(null)}>
                <DialogContent className="max-w-7xl p-0 overflow-hidden border-none bg-black/95 backdrop-blur-3xl shadow-[0_0_100px_rgba(0,0,0,0.8)]">
                    <DialogTitle className="sr-only">Zoomed Storyboard Image</DialogTitle>
                    <div className="relative w-full h-full flex items-center justify-center p-4">
                        {zoomedImage && (
                            <img
                                src={zoomedImage}
                                alt="Zoomed Cinematography"
                                className="max-w-full max-h-[85vh] object-contain rounded-lg shadow-2xl animate-in zoom-in-95 duration-300"
                            />
                        )}
                        <Button
                            variant="ghost"
                            size="icon"
                            className="absolute top-4 right-4 h-12 w-12 rounded-full bg-white/5 hover:bg-white/10 text-white/50 hover:text-white transition-all backdrop-blur-md"
                            onClick={() => setZoomedImage(null)}
                        >
                            <X className="h-6 w-6" />
                        </Button>


                    </div>
                </DialogContent>
            </Dialog>
        </div>
    );
}
